server:
  port: 8080

spring:
  application:
    name: redsignal
  datasource:
    url: jdbc:h2:~/devcv;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: false

jasypt:
  encryptor:
    key: ${PDF_JASYPT_ENCRYPTOR_KEY:}

